apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  namespace: knative-serving
data:
  backend: zipkin
  zipkin-endpoint: http://otel-collector.observability:9411/api/v2/spans
  debug: "true"