controller:
  electionID: external-ingress-controller-leader
  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false    
    controllerValue: "k8s.io/nginx-external"
  admissionWebhooks:
    patch:
      tolerations:
      - effect: NoSchedule
        key: app-type
        operator: Equal
        value: cb-core
      nodeSelector:
        kubernetes.io/os: linux
  nodeSelector:
    kubernetes.io/os: linux
  replicaCount: 2
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  ingressClass: nginx-external  
  tolerations:
    - effect: NoSchedule
      key: app-type
      operator: Equal
      value: cb-core