name: az-tf-plan

on:    
  pull_request:
    paths:
      - 'azure/terraform/**'
        
env:
  TF_INPUT: 0
  TF_PATH: 'azure/terraform/cb_core'
  TF_VAR_github_token: ${{ secrets.GIT_TOKEN }}
  CLOUDAMQP_APIKEY: ${{ secrets.CLOUDAMQP_APIKEY }}

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          service: [ "cb-backend", "knative", "helm-charts"  ]
          env: ["dev", "qa", "production"]

    env:
      TF_ENV: ${{ matrix.service }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

    environment:
      name: ${{ matrix.env }}
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform fmt
        id: fmt
        working-directory: ${{ env.TF_PATH }}
        run: terraform fmt -check
        
      - name: Git Config Update
        run: git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com".insteadOf https://github.com

      - name: Check TF Plan
        working-directory: '${{ env.TF_PATH }}/${{ env.TF_ENV }}' 
        run: | 
          terraform init -reconfigure -backend-config=backend/${{ matrix.env }}
          terraform plan -var environment=${{ matrix.env }}
  
  tf-plan-shared:
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    
    environment: shared
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform fmt
        id: fmt
        working-directory: 'azure/terraform/cb_core/cb-eslz' 
        run: terraform fmt -check
        
      - name: Git Config Update
        run: git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com".insteadOf https://github.com

      - name: Check TF Plan
        working-directory: 'azure/terraform/cb_core/cb-eslz' 
        run: | 
          terraform init -reconfigure -backend-config=backend/shared
          terraform plan -var environment=shared

  tf-plan-global:
    runs-on: ubuntu-latest

    environment: global
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform fmt
        id: fmt
        working-directory: 'azure/terraform/cb_core/global' 
        run: terraform fmt -check
        
      - name: Git Config Update
        run: git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com".insteadOf https://github.com

      - name: Check TF Plan
        working-directory: 'azure/terraform/cb_core/global' 
        run: | 
          terraform init -reconfigure -backend-config=backend/global
          terraform plan